apiVersion: apps/v1
kind: Deployment
metadata:
  name: sui-archive-${sui_network}${sui_shard}
spec:
  selector:
    matchLabels:
      app: sui-archive-${sui_network}${sui_shard}
  template:
    metadata:
      labels:
        app: sui-archive-${sui_network}${sui_shard}
    spec:
      containers:
      - name: sui-archive
        image: "${image_sui_archive}"
        env:
        - name: PGPASSWORD
          value: "${db_password_sui_archive}"
        - name: PGHOST
          value: "${db_host}"
        - name: PGDATABASE
          value: "${namespace}"
        - name: SUI_ARCHIVE_SCHEMA
          value: "sui_${sui_network}${sui_shard}"
        - name: PGUSER
          value: "sui_archive"
#        - name: SUI_ARCHIVE_CRON_SECONDS
#          value: "86400"
#        - name: SUI_ARCHIVE_START_TIME
#          value: "2023-04-14T00:00:00Z"
#        - name: SUI_ARCHIVE_END_TIME
#          value: "2023-04-15T00:00:00Z"
        - name: SUI_ARCHIVE_CURSOR_TXDIGEST
          value: "${sui_cursor}"
        - name: SUI_ARCHIVE_CURSOR_EVENTSEQ
          value: "0"
        - name: SUI_ARCHIVE_ENDPOINT
#          value: "https://fullnode.${sui_network}.sui.io"
          value: "http://sui-${sui_network}:9000"
#        resources:
#          limits:
#            memory: "1024Mi"
##            cpu: "1000m"
#          requests:
#            memory: "200Mi"
##            cpu: "100m"

